#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  test_colorkey_on_red.sh PROCESSED_VIDEO OUTPUT_MP4 [options]

Options:
  --mask PATH         Mask video generated by remove_black_background.sh
  --bg-color COLOR    Background color for test composite (default: red)
  --crf N             Output quality for h264 (default: 18)
  -h, --help          Show help

Examples:
  ./scripts/test_colorkey_on_red.sh out.mp4 out_test_red.mp4
  ./scripts/test_colorkey_on_red.sh out.mp4 out_test_red.mp4 --mask out_mask.mp4

Notes:
  - This script does not key colors. It tests already-processed output.
  - For mp4/h264 processed output, pass a mask (or rely on auto-detect).
EOF
}

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "Error: ffmpeg is required but not found in PATH."
  exit 1
fi

if ! command -v ffprobe >/dev/null 2>&1; then
  echo "Error: ffprobe is required but not found in PATH."
  exit 1
fi

INPUT="$1"
OUTPUT="$2"
shift 2

MASK=""
BG_COLOR="red"
CRF="18"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mask)
      MASK="${2:-}"
      shift 2
      ;;
    --bg-color)
      BG_COLOR="${2:-}"
      shift 2
      ;;
    --crf)
      CRF="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ ! -f "$INPUT" ]]; then
  echo "Error: input file not found: $INPUT"
  exit 1
fi

if [[ -z "${MASK}" ]]; then
  auto_mask_1="${INPUT%.*}_mask.mp4"
  auto_mask_2="${INPUT%.*}.mask.mp4"
  if [[ -f "${auto_mask_1}" ]]; then
    MASK="${auto_mask_1}"
  elif [[ -f "${auto_mask_2}" ]]; then
    MASK="${auto_mask_2}"
  fi
fi

WIDTH="$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of csv=p=0 "$INPUT" | head -n1)"
HEIGHT="$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of csv=p=0 "$INPUT" | head -n1)"
FPS="$(ffprobe -v error -select_streams v:0 -show_entries stream=avg_frame_rate -of csv=p=0 "$INPUT" | head -n1)"
PIXFMT="$(ffprobe -v error -select_streams v:0 -show_entries stream=pix_fmt -of csv=p=0 "$INPUT" | head -n1)"

if [[ -z "${WIDTH}" || -z "${HEIGHT}" ]]; then
  echo "Error: failed to read input video dimensions."
  exit 1
fi

if [[ -z "${FPS}" || "${FPS}" == "0/0" ]]; then
  FPS="30"
fi

if [[ -n "${MASK}" && ! -f "${MASK}" ]]; then
  echo "Error: mask file not found: ${MASK}"
  exit 1
fi

if [[ -n "${MASK}" ]]; then
  ffmpeg -y \
    -i "$INPUT" \
    -i "$MASK" \
    -f lavfi -i "color=c=${BG_COLOR}:s=${WIDTH}x${HEIGHT}:r=${FPS}" \
    -filter_complex "[0:v]format=rgb24[fg];[1:v]format=gray[m];[fg][m]alphamerge[fg_a];[2:v]format=rgba[bg];[bg][fg_a]overlay=shortest=1[v]" \
    -map "[v]" \
    -map 0:a? \
    -c:v libx264 -pix_fmt yuv420p -crf "$CRF" \
    -c:a aac -strict -2 -shortest \
    "$OUTPUT"
else
  case "${PIXFMT}" in
    yuva*|rgba|bgra|argb|abgr)
      ffmpeg -y \
        -i "$INPUT" \
        -f lavfi -i "color=c=${BG_COLOR}:s=${WIDTH}x${HEIGHT}:r=${FPS}" \
        -filter_complex "[0:v]format=rgba[fg];[1:v]format=rgba[bg];[bg][fg]overlay=shortest=1[v]" \
        -map "[v]" \
        -map 0:a? \
        -c:v libx264 -pix_fmt yuv420p -crf "$CRF" \
        -c:a aac -strict -2 -shortest \
        "$OUTPUT"
      ;;
    *)
      echo "Error: no mask provided and input pixel format '${PIXFMT}' has no alpha."
      echo "Provide --mask PATH (or run remove_black_background.sh with h264 to auto-create *_mask.mp4)."
      exit 1
      ;;
  esac
fi

echo "Done."
echo "  Input:  $INPUT"
if [[ -n "${MASK}" ]]; then
  echo "  Mask:   $MASK"
fi
echo "  Output: $OUTPUT"
echo "  BG:     ${BG_COLOR}"
